spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  #RabbitMQ
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8030

jwt:
  secret: abc
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

wx:
  appid: "xx"
  secret: "xx"
