spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: ff0f6e94-b1ac-41a8-8adb-5dad8ba6736f
        cluster-name: BJ
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1

  application:
    name: content-center

  main:
    allow-bean-definition-overriding: true

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#默认使用懒加载，改为饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.chengshare: debug
    #feign的日志级别建立在feign接口是debug级别之上的
    com.chengshare.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 全局配置 /指定服务名
      default: #user-center:
        LoggerLevel: full


