server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: after_route
          uri: lb://user-center
          predicates:
            - After=2010-01-20T17:42:47.789-07:00[America/Denver]
            - TimeBetween=上午9:00, 下午5:00
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
