server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: after_route
          uri: lb://user-center
          predicates:
            - After=2010-01-20T17:42:47.789-07:00[America/Denver]
            - TimeBetween=上午9:00, 下午5:00
          #GatewayFilter Factories https://www.imooc.com/article/290816
          #filter的断点调试org.springframework.cloud.gateway.filter.NettyRoutingFilter.filter
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a, b

#/actuator/gateway/下
# globalfilters 展示所有的全局过滤器
# routefilters 展示所有的过滤器工厂
# routes  展示路由列表
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    #gateway请求细节
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug